version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data/
    env_file:
      - .env

  django:
    build: ./app
    restart: always
    volumes:
      - static_value:/opt/app/static/
      - media_value:/opt/app/media/
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./data:/data/:ro
      - static_value:/opt/app/static/
      - media_value:/opt/app/media/
    depends_on:
      - django
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_value:
  media_value:
